version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  deploy:
    docker:
      - image: cimg/node:13.11.0
    steps:
      - checkout
      - run: npm deploy
workflows:
  node-tests:
    jobs:
      - node/test
      - deploy
